import Navbar from './components/Navbar'
import Hero from './components/Hero'
import About from './components/About'
import Skills from './components/Skills'
import Experience from './components/Experience'
import Projects from './components/Projects'
import WhyHireMe from './components/WhyHireMe'
import Contact from './components/Contact'
import Footer from './components/Footer'
export default function App(){return <div className="min-h-screen bg-slate-50"><Navbar/><main><Hero/><About/><Skills/><Experience/><Projects/><WhyHireMe/><Contact/></main><Footer/></div>}
